[package]
name = "kumir_gui_docs_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "*"
quote = "*"
syn = "*"

egui_commonmark = {workspace=true}
egui = {workspace = true}

[lib]
proc-macro = true
