[package]
name = "kumir3"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
egui-wgpu = { version = "0.31.1", features = ["winit"] }
egui-winit = "0.31.1"
winit = "0.30.9"
pollster = "0.4.0"
